# Site settings
title: Jonathan Lapham
email: jonathan@lapham.org.uk
author: Jonathan Lapham
description:
url: www.lapham.org.uk

# Build settings
markdown: kramdown
permalink: /notes/:year/:month/:day/:title
plugins:
  - jekyll-feed
# permalink: :title/
sass:
  sass_dir: css

header_pages:
  - notes.md
  - pgp.md
  - about.md

contact_links:
  - name: "LinkedIn"
    icon: "bi-linkedin"
    href: "https://www.linkedin.com/in/jonathanlapham"
  - name: "Facebook"
    icon: "bi-facebook"
    href: "https://www.facebook.com/jonathan.lapham"
  - name: "Email"
    icon: "bi-envelope"
    href: "&#109;ai&#108;to&#58;jon&#97;%74&#104;%&#54;1&#37;&#54;E&#64;la%70ham&#46;org.uk"
  - name: "PGP Key"
    icon: "bi-key"
    href: "pgp"
