# Site settings
title: Jonathan Lapham
email: jonathan@lapham.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Jonathan Lapham personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lapham.org.uk" # the base hostname & protocol for your site
github_username:  jonathanlapham

permalink: /notes/:year/:month/:day/:title
# Build settings
markdown: kramdown
